### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by KagamiChan** [KagamiChan/toaru#1]
## Development
- [ ] port existing js
- [ ] built-in PNG optimization
- [ ] built-in SVG optimization

## Localization
- [ ] multi language support

## Misc
- [ ] licenses
- [ ] credits/links
